# .github/workflows/daily-scrape.yml
name: Daily Scrape & Dashboard

# give Actions permission to deploy via the Pages API
permissions:
  contents: write # for checkout, reading/writing CSV
  pages: write # to deploy via actions/deploy-pages
  id-token: write # required by actions/deploy-pages@v4

on:
  push:
    branches:
      - main
    paths-ignore:
      - today_listings.csv
      - historical_listings.csv
      - docs/**
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 pandas matplotlib tqdm

      - name: Scrape listings
        run: python scraper.py

      - name: Merge & dedupe
        shell: bash
        run: |
          python - << 'EOF'
          import pandas as pd, os

          today = pd.read_csv("today_listings.csv")
          if os.path.exists("historical_listings.csv"):
              hist = pd.read_csv("historical_listings.csv")
              combined = pd.concat([hist, today], ignore_index=True)
          else:
              combined = today

          combined.drop_duplicates(subset=["scrape_date","listing_url"], inplace=True)
          combined.to_csv("historical_listings.csv", index=False)
          EOF

      - name: Generate Dashboard
        run: python generate_dashboard.py
        env:
          TZ: Europe/Tirane

      # ──────────────────────────────────────────────────────────────────────
      # Now: deploy via the Pages API instead of pushing to gh-pages branch
      # ──────────────────────────────────────────────────────────────────────

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
